# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: number_square.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13number_square.proto\x12\x03num\"\x19\n\x07request\x12\x0e\n\x06number\x18\x01 \x01(\t\"\x17\n\x05reply\x12\x0e\n\x06square\x18\x01 \x01(\t24\n\x06square\x12*\n\nnum_square\x12\x0c.num.request\x1a\n.num.reply(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'number_square_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=28
  _globals['_REQUEST']._serialized_end=53
  _globals['_REPLY']._serialized_start=55
  _globals['_REPLY']._serialized_end=78
  _globals['_SQUARE']._serialized_start=80
  _globals['_SQUARE']._serialized_end=132
# @@protoc_insertion_point(module_scope)
